### ISSUE TITLE
Unable to locate right intro message on server join

### ISSUE THREAD

**Issue by AsboniaTV** [MaDmaX1337/GamersCentral.de-AW-Invade-Annex#2]
Where can I locate and edit/remove this message; 
![4d569809e51a683d37c12325bfd86696](https://cloud.githubusercontent.com/assets/12697419/17837836/1dd5fd4c-67be-11e6-8f28-f39d6b84b955.png)

**Comment by TheFrozenThr0ne** [comment]
Here at our Steam Workshop File share are information at bottom what pictures and what scripts with gamerscentral names will called. http://steamcommunity.com/sharedfiles/filedetails/?id=664646936

How to adjust the Text for your Community

Zeus Enabled 
To use Zeus, you have to open this Mission in the Eden Editor. 

Create a folder called something.Altis put the Mission Files in it. 
Subsequently copy the folder into your X:\Users\YourName\Documents\Arma 3\missions folder and open the Mission in the Eden Editor. 

In the middle of the Map you will find the Zeus Modules just open it up one of them and Edit the Name and the UID - Save mission and youre good to go. 

Other Text and Pictures 
Once you have it on the Editor you can change the Marker Text Names NOT the Marker Name itself. 
Some other Text can be found here: 
description.ext 
\scripts\ta\gcmessage.sqf 
\misc\member.sqf 
\misc\noMember.sqf 

Pictures 
\scripts\ta\gc.paa 
\media\images\billboard.jpg 
\media\images\billboardads.jpg 
\media\images\GCFlag.jpg 
\media\images\loading.jpg

**Comment by TheFrozenThr0ne** [comment]
what youre looking for is in: \scripts\ta\gcmessage.sqf

**Comment by AsboniaTV** [comment]
Thank you!! <3

**Comment by TheFrozenThr0ne** [comment]
Youre Welcome

**Comment by AsboniaTV** [comment]
One last thing xD In the map, "Teamspeak" tab, where can I find and edit info on that?

**Comment by TheFrozenThr0ne** [comment]
Sorry i dont know what u mean? If its a Marker then you can do it in the Eden Editor.

**Comment by TheFrozenThr0ne** [comment]
Ah maybe u mean the info tabs - MissionFolder\GamersCentralDE.sqf and or MissionFolder\scripts\misc\diary.sqf

**Comment by TheFrozenThr0ne** [comment]
But please dont remove the credits - i mean Edited by MaDmaX [GC]
