### ISSUE TITLE
Enemy AI not spawning in properly?

### ISSUE THREAD

**Issue by AsboniaTV** [MaDmaX1337/GamersCentral.de-AW-Invade-Annex#3]
Just noticed only squad leaders of AI squads are visible, every other AI is hidden/invisible?

![14fb86e77581d1d1e37c1fd75cc91831](https://cloud.githubusercontent.com/assets/12697419/17908891/82ceb32c-6982-11e6-9b99-d10779f53df1.jpg)
![52c070e492bc28c84551a63601a22b00](https://cloud.githubusercontent.com/assets/12697419/17908890/82ce26d2-6982-11e6-87fd-0236820336be.jpg)
![205f6263d5ea3d627f809812cb4f52a6](https://cloud.githubusercontent.com/assets/12697419/17908893/82d00402-6982-11e6-8692-43f7563a3578.jpg)
![5fa31730658e37c618e68db8b05fad4a](https://cloud.githubusercontent.com/assets/12697419/17908892/82ceba84-6982-11e6-9d9b-033c69ea0fcb.png)

How to fix?

**Comment by TheFrozenThr0ne** [comment]
This is Unit Caching (zbe_cache) to have a bit more fps, it will be visible when blufor are nerby. Disable in init.sqf or add // before line:

//if (isServer) then {[1000,-1,false,100,1000,1000]execvm "zbe_cache\main.sqf"};
